env:
  - VERSION=0.9

language: go

before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr
script:
  - go test -v ./...
after_success:
  - gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
  - ghr --username vfarcic --token $GITHUB_TOKEN --replace --debug v${VERSION} dist/

branches:
  only:
    - master
