language: go

before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr
script:
  - go test -v ./...
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}/{{.Dir}}"
  - ghr --username vfarcic --token $GITHUB_TOKEN --replace --debug v0.1.0 dist/